apiVersion: v1
kind: Secret
metadata:
  name: vault-unsealer-keys
  namespace: {{ .Values.namespace }}
  labels:
    app: vault-unsealer
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- $keys := .Values.vault.unsealKeys }}
{{- range $i, $v := $keys }}
  key{{ add $i 1 }}: {{ $v | b64enc }}
{{- end }}